apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file ../docker-compose-resolved.yml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: dspaces
  name: dspaces
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dspaces
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file ../docker-compose-resolved.yml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: dspaces
    spec:
      containers:
        - env:
            - name: DSPACES_DEBUG
              value: "1"
            - name: DSPACES_SERVER_CHECKOUT
              value: v2.3.0-beta
            - name: DSPACES_SERVER_PORT
              value: "4000"
            - name: OFI_STRING
              value: tcp://eth0:4000
            - name: REPO_BRANCH
              value: v2.3.0-beta
          image: philipdavis/dspaces-server:v01082024
          livenessProbe:
            exec:
              command:
                - nc
                - -z
                - dspaces
                - "4000"
          name: dspaces
          ports:
            - containerPort: 4000
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /dspaces.toml
              name: dspaces-cm
              subPath: dspaces.toml
            - mountPath: /dspaces_reg.db
              name: dspaces-cm
              subPath: dspaces_reg.db
      volumes:
        - name: dspaces-cm
          configMap:
            name: dspaces-cm
      restartPolicy: Always
      