apiVersion: apps/v1
kind: Deployment
metadata:
  name: dspaces-server
  namespace: dspaces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dspaces-server
  template:
    metadata:
      labels:
        app: dspaces-server
    spec:
      containers:
        - name: dspaces-server
          image: philipdavis/dspaces-server:v01082024
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
              protocol: TCP
          env:
            - name: DSPACES_DEBUG
              value: "1"
            - name: DSPACES_SERVER_CHECKOUT
              value: v2.3.0-beta
            - name: DSPACES_SERVER_PORT
              value: "4000"
            - name: REPO_BRANCH
              value: v2.3.0-beta
            - name: OFI_STRING
              value: tcp://eth0:4000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /dspaces.toml
              name: dspaces-cm
              subPath: dspaces.toml
            - mountPath: /dspaces_reg.db
              name: db-volume
              subPath: dspaces_reg.db

      # Create database file before starting the server
      # Mount the db file to shared volume
      initContainers:
        - name: init-database
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              echo "Initializing dspaces_reg.db...";
              touch /mnt/dspaces_reg.db;
              cat /mnt/dspaces_reg.db;
              chmod 666 /mnt/dspaces_reg.db; # Set permissions
          volumeMounts:
            - name: db-volume
              mountPath: /mnt

      volumes:
        - name: dspaces-cm
          configMap:
            name: dspaces-cm
        - name: db-volume
          emptyDir: {}
      restartPolicy: Always
