apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dspaces-api-ingress
  namespace: dspaces
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /dspaces(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dspaces-api-service
                port:
                  number: 8001
