apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dspace-api-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /dspace(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dspace-api-service
                port:
                  number: 8001
