apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pop-api
  template:
    metadata:
      labels:
        app: pop-api
    spec:
      containers:
      - name: pop-api
        image: yutianqin/pop-api:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env: 
        - name: RUNNING_IN_INGRESS
          value: "true"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: env-volume
          mountPath: /code/env_variables/
      volumes:
      - name: env-volume
        secret:
          secretName: pop-env-secret
