apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pop-api-ingress
  namespace: pop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /pop(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: pop-api-service
                port:
                  number: 8001
