apiVersion: v1
kind: Service
metadata:
  name: pop-api-service
  labels:
    app: pop-api
spec:
  selector:
    app: pop-api
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000
  type: ClusterIP
