apiVersion: v1
kind: Service
metadata:
  name: ndp-ep-api-service
  labels:
    app: ndp-ep-api
spec:
  selector:
    app: ndp-ep-api
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8000
  type: ClusterIP
