apiVersion: v1
appVersion: "1.0"
description: A deployment chart for a JupyterHub
name: scidx-jhub
version: 0.1.0
dependencies:
- name: jupyterhub
  version: "v2.0.0"
  repository: https://jupyterhub.github.io/helm-chart/