apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ndp-ep-api-ingress
  namespace: ndp-ep
spec:
  ingressClassName: public # change me
  rules:
    - host: ndp-dev-202.chpc.utah.edu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ndp-ep-api-service
                port:
                  number: 8003
